### ISSUE TITLE
Switcheroo软件可否提供exe程序

### ISSUE THREAD

**Issue by huo-feng-ding** [windedge/Scooper#1]
您好，我看到您对 https://github.com/windedge/Switcheroo 这个软件有更新，最近我也在用这个软件，可是在使用过程中有些问题，发现您对此软件有做过修改更新，能否打包一份新的exe文件。 我本地没有vs开发平台，不会处理。谢谢

**Comment by windedge** [comment]
https://github.com/windedge/Switcheroo/releases/tag/windedge-v0.1

这个修改主要是限制只能切换当前桌面的窗口，对dotnet不熟，获取窗口的列表有点问题，有空再完善下。

**Comment by huo-feng-ding** [comment]
收到，十分感谢
