### ISSUE TITLE
scooper can't find my scoop

### ISSUE THREAD

**Issue by lpeng108561** [windedge/Scooper#3]
I install scoop to a custom directory, and scooper can't find it.
![屏幕截图 2024-06-18 214639](https://github.com/windedge/Scooper/assets/104988443/4b35e704-9a69-4942-9fc0-3e110ed34272)

**Comment by windedge** [comment]
Can you check if the environment variables `SCOOP` and `SCOOP_GLOBAL` are set?

**Comment by lpeng108561** [comment]
It works.Thanks.

**Comment by Raizanad** [comment]
@windedge probably an abandoned project, but Scoop no longer actively recommend setting such variables. It is now found in the scoop config.
